### ISSUE TITLE
Add docs for "Create disk from .vhdx file" & unable to create from .vhdx file

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/h1-cli#44] opened 2018-06-12 02:24 UTC
This doesn't work. I am unable to debug that, so assign to @fredericosilva .

**Comment by fredericosilva** [comment] 2018-06-12 02:30
You are talking about vhdx, right?

Can you attach error log here? It might be helpful for future reference.

**Comment by ad-m** [comment] 2018-06-12 02:41
Yes, of course.

```
$ h1 disk create --name my-cool-disk --type ssd --size 1
ID                        NAME          TYPE  SIZE  STATE     PROCESSING
5b1f31badadb705edd76b523  my-cool-disk  ssd   1     Detached  false
$ time h1 disk download --disk 5b1f31badadb705edd76b523 --destination-file my-disk.vhdx

  downloading [========================================================================================================================================================================================================] 5262615/Bps 100% 0.0s

real	0m2.272s
user	0m0.924s
sys	0m0.112s
$ h1 disk create --name my-cool-disk --type ssd --size 1 --source-file my-disk.vhdx --verbose
verbose: ws wss://api.hyperone.com/ws
verbose: websocket opened
verbose: body
{
  "name": "my-cool-disk",
  "service": "ssd",
  "size": 1,
  "metadata": {
    "source": {
      "filename": "my-disk.vhdx",
      "size": 4194304
    }
  }
}
verbose: POST https://api.hyperone.com/v1/disk
verbose: headers
{
  "server": "nginx",
  "date": "Tue, 12 Jun 2018 02:38:41 GMT",
  "content-type": "application/json; charset=utf-8",
  "content-length": "669",
  "connection": "close",
  "set-cookie": [
    "x-auth-token={...}; Path=/; Expires=Tue, 12 Jun 2018 03:38:24 GMT; HttpOnly; Secure"
  ],
  "etag": "{...}"
}
verbose: 202 event queued, waiting for completion....
verbose: state: processing {"count":2,"current":2}
verbose: state: finished 
verbose: ws wss://download.hyperone.com/ws/disk/5b1f3231dadb705edd76b52b/upload
verbose: websocket opened
waiting for the OK to upload
received "file is missing"
error: "file is missing"
$ ls -lah my-disk.vhdx 
-rw-rw-r-- 1 adas adas 4,0M cze 12 04:37 my-disk.vhdx
$ xxd my-disk.vhdx | head -n 20
00000000: 7668 6478 6669 6c65 4d00 6900 6300 7200  vhdxfileM.i.c.r.
00000010: 6f00 7300 6f00 6600 7400 2000 5700 6900  o.s.o.f.t. .W.i.
00000020: 6e00 6400 6f00 7700 7300 2000 3100 3000  n.d.o.w.s. .1.0.
00000030: 2e00 3000 2e00 3100 3400 3300 3900 3300  ..0...1.4.3.9.3.
00000040: 2e00 3000 0000 0000 0000 0000 0000 0000  ..0.............
00000050: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000060: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000070: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000080: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000090: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000a0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000b0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000c0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000d0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000e0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
000000f0: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000100: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000110: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000120: 0000 0000 0000 0000 0000 0000 0000 0000  ................
00000130: 0000 0000 0000 0000 0000 0000 0000 0000  ................
```

**Comment by fredericosilva** [comment] 2018-06-13 15:13
@ad-m fixed on the infrastructure

Now the problem is on the CLI side
```
$ h1 disk create --name test-disk-1 --type ssd --size 2 --source out.vhdx
waiting for the OK to upload
received OK 0

  uploading [==============================================================] 1721800/Bps 100% 0.0s


...\h1-cli\node_modules\ws-streamify\lib\index.js:105
          throw new Error('Unsupported message type');
          ^

Error: Unsupported message type
    at WebSocketStream.socket.onmessage (...\h1-cli\node_modules\ws-streamify\lib\index.js:105:17)
    at WebSocket.onMessage (...\h1-cli\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:182:13)
    at Receiver.receiverOnMessage (...\h1-cli\node_modules\ws\lib\websocket.js:718:20)
    at Receiver.emit (events.js:182:13)
    at Receiver.dataMessage (...\h1-cli\node_modules\ws\lib\receiver.js:405:14)
    at Receiver.getData (...\h1-cli\node_modules\ws\lib\receiver.js:346:17)
    at Receiver.startLoop (...\h1-cli\node_modules\ws\lib\receiver.js:133:22)
    at Receiver._write (...\h1-cli\node_modules\ws\lib\receiver.js:69:10)
    at doWrite (_stream_writable.js:410:12)
    at writeOrBuffer (_stream_writable.js:394:5)
    at Receiver.Writable.write (_stream_writable.js:294:11)
    at TLSSocket.socketOnData (...\h1-cli\node_modules\ws\lib\websocket.js:788:35)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
```

Going to assign the issue to you

**Comment by ad-m** [comment] 2018-06-15 12:12
I verified the reason of that. There is no issue on client-side. Servers send data, next to send empty messages which fails on client data. The server should send END after data, not empty messages. The server never sends END.

https://github.com/baygeldin/ws-streamify/blob/master/src/index.js#L70 

This is a server-side issue that I do not know yet, so going to assing the issue to you.

**Comment by fredericosilva** [comment] 2018-07-05 13:13
@ad-m the END is sent internally by

https://github.com/baygeldin/ws-streamify/blob/master/src/index.js#L30

going to add a workaround, maybe we should ditch this module

**Closed** 2018-07-10 10:02 UTC
Labels: bug
